// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	snapshot: () => typedError<SnapshotDto, ApiErrorDto>(__TAURI_INVOKE("snapshot")),
	refresh: (request: RefreshRequestDto) => typedError<SnapshotDto, ApiErrorDto>(__TAURI_INVOKE("refresh", { request })),
	preview: (request: PreviewRequestDto) => typedError<UpdatePlanDto[], ApiErrorDto>(__TAURI_INVOKE("preview", { request })),
	confirm: (request: ConfirmRequestDto) => typedError<ConfirmResponseDto, ApiErrorDto>(__TAURI_INVOKE("confirm", { request })),
	cancel: (request: CancelRequestDto) => typedError<CancelResponseDto, ApiErrorDto>(__TAURI_INVOKE("cancel", { request })),
	runHistory: () => typedError<RunHistoryDto, ApiErrorDto>(__TAURI_INVOKE("run_history")),
	runLog: (request: RunLogRequestDto) => typedError<RunLogDto, ApiErrorDto>(__TAURI_INVOKE("run_log", { request })),
	settings: () => typedError<SettingsDocumentDto, ApiErrorDto>(__TAURI_INVOKE("settings")),
	saveSettings: (request: SaveSettingsRequestDto) => typedError<SettingsDocumentDto, ApiErrorDto>(__TAURI_INVOKE("save_settings", { request })),
	validateManifest: (request: ManifestInputDto) => typedError<ManifestValidationDto, ApiErrorDto>(__TAURI_INVOKE("validate_manifest", { request })),
	readManifest: (request: ManifestReadRequestDto) => typedError<ManifestDocumentDto, ApiErrorDto>(__TAURI_INVOKE("read_manifest", { request })),
	saveManifest: (request: SaveManifestRequestDto) => typedError<SavedManifestDto, ApiErrorDto>(__TAURI_INVOKE("save_manifest", { request })),
	listAgentTargets: () => typedError<AgentTarget[], ApiErrorDto>(__TAURI_INVOKE("list_agent_targets")),
	saveAgentTargets: (request: SaveAgentsRequest) => typedError<AgentTarget[], ApiErrorDto>(__TAURI_INVOKE("save_agent_targets", { request })),
	listSkills: () => typedError<SkillsSnapshot, ApiErrorDto>(__TAURI_INVOKE("list_skills")),
	listSkillSources: () => typedError<SkillsSnapshot, ApiErrorDto>(__TAURI_INVOKE("list_skill_sources")),
	saveSkillSource: (request: SaveSourceRequest) => typedError<SkillsSnapshot, ApiErrorDto>(__TAURI_INVOKE("save_skill_source", { request })),
	deleteSkillSource: (request: DeleteSourceRequest) => typedError<SkillsSnapshot, ApiErrorDto>(__TAURI_INVOKE("delete_skill_source", { request })),
	discoverSkills: (request: DiscoverRequest) => typedError<SkillDiscovery, ApiErrorDto>(__TAURI_INVOKE("discover_skills", { request })),
	searchSkills: (request: SearchRequest) => typedError<SearchSkill[], ApiErrorDto>(__TAURI_INVOKE("search_skills", { request })),
	scanSkillImports: () => typedError<SkillDiscovery, ApiErrorDto>(__TAURI_INVOKE("scan_skill_imports")),
	checkSkillUpdates: (request: CheckUpdatesRequest) => typedError<SkillUpdate[], ApiErrorDto>(__TAURI_INVOKE("check_skill_updates", { request })),
	listSkillBackups: () => typedError<ExtensionBackup[], ApiErrorDto>(__TAURI_INVOKE("list_skill_backups")),
	previewSkillOperation: (request: SkillOperationRequest) => typedError<ExtensionPlan, ApiErrorDto>(__TAURI_INVOKE("preview_skill_operation", { request })),
	listMcpServers: () => typedError<McpSnapshot, ApiErrorDto>(__TAURI_INVOKE("list_mcp_servers")),
	scanMcpImports: () => typedError<McpScan, ApiErrorDto>(__TAURI_INVOKE("scan_mcp_imports")),
	validateMcpServer: (request: McpEdit) => typedError<Diagnostic[], ApiErrorDto>(__TAURI_INVOKE("validate_mcp_server", { request })),
	previewMcpOperation: (request: McpOperationRequest) => typedError<ExtensionPlan, ApiErrorDto>(__TAURI_INVOKE("preview_mcp_operation", { request })),
	confirmExtensionOperation: (request: ConfirmExtensionRequest) => typedError<ExtensionStarted, ApiErrorDto>(__TAURI_INVOKE("confirm_extension_operation", { request })),
	extensionOperationResult: (request: IdRequest) => typedError<ExtensionResult, ApiErrorDto>(__TAURI_INVOKE("extension_operation_result", { request })),
};

/** Events */
export const events = {
	mcpChanged: makeEvent<McpChangedEventDto>("mcp-changed"),
	refreshProgress: makeEvent<RefreshProgressEventDto>("refresh-progress"),
	runOutput: makeEvent<RunOutputEventDto>("run-output"),
	runState: makeEvent<RunStateEventDto>("run-state"),
	skillsChanged: makeEvent<ExtensionChangedEventDto>("skills-changed"),
	toolState: makeEvent<ToolStateEventDto>("tool-state"),
};

/* Types */
export type AgentOverride = {
	skillsDir: string | null,
	mcpFile: string | null,
};

export type AgentTarget = {
	id: string,
	name: string,
	scope: string,
	skillsDir: string,
	mcpFile: string,
	pathSource: string,
	available: boolean,
	transports: McpTransport[],
	sharedWith: string[],
	scanDirs: string[],
};

export type ApiErrorCode = "invalid_request" | "not_found" | "invalid_plan" | "conflict" | "unavailable" | "internal";

export type ApiErrorDto = {
	code: ApiErrorCode,
	message: string,
	retryable: boolean,
	details: { [key in string]: string },
};

export type CancelDispositionDto = "cancellation_requested" | "already_finished";

export type CancelRequestDto = {
	runId: string,
};

export type CancelResponseDto = {
	runId: string,
	disposition: CancelDispositionDto,
};

export type CatalogDiagnosticDto = {
	source: string,
	manifestId: string,
	kind: string,
	matchingToolIds: string[],
	message: string,
};

export type CatalogErrorDto = {
	source: string,
	fieldPath: string,
	kind: string,
	message: string,
	hint: string,
	line: number | null,
	column: number | null,
};

export type CheckUpdatesRequest = {
	requestId: string,
	skillIds: string[],
};

export type CommandSpecDto = {
	program: string,
	args: string[],
	cwd: string | null,
	env: { [key in string]: EnvironmentValueDto },
	timeoutSeconds: string,
	successExitCodes: number[],
	networkRequired: boolean,
	postCheck: CommandSpecDto | null,
	displayCommand: string,
};

export type ComponentDto = {
	id: string,
	displayName: string,
	installationId: string | null,
	strategies: StrategyDto[],
	defaultStrategy: string | null,
	installedVersion: string | null,
	latestVersion: string | null,
	status: ComponentStatusDto,
};

export type ComponentStatusDto = {
	status: string,
	reason: StatusReasonDto | null,
	verification: VerificationStatusDto | null,
};

export type ConfirmExtensionRequest = {
	planId: string,
	planHash: string,
};

export type ConfirmRequestDto = {
	planId: string,
	planHash: string,
};

export type ConfirmResponseDto = {
	execution: ExecutionResultDto,
	snapshot: SnapshotDto,
};

export type DeleteSourceRequest = {
	expectedRevision: string,
	sourceId: string,
};

export type DeployMode = "auto" | "copy" | "symlink" | "external";

export type Diagnostic = {
	targetId: string,
	message: string,
};

export type DiscoverRequest = {
	requestId: string,
	source: SkillSource,
};

export type EnvironmentValueDto = {
	value: string,
	sensitive: boolean,
};

export type ExecutableDto = {
	name: string,
	path: string,
};

export type ExecutionResultDto = {
	runId: string,
	status: string,
	exitCode: number | null,
	startedAt: string,
	finishedAt: string,
	outputTail: string,
	verification: VerificationStatusDto | null,
};

export type ExtensionBackup = {
	id: string,
	resource: ResourceKind,
	operation: string,
	names: string[],
	createdAt: string,
	status: string,
	sizeBytes: string,
};

export type ExtensionChangedEventDto = {
	revision: string,
	sequence: string,
	runId: string,
	resourceIds: string[],
};

export type ExtensionPlan = {
	planId: string,
	planHash: string,
	resource: ResourceKind,
	operation: string,
	names: string[],
	expiresAt: string,
	steps: OperationStepView[],
	warnings: string[],
};

export type ExtensionResult = {
	runId: string,
	status: string,
	targets: TargetResult[],
	backupId: string | null,
};

export type ExtensionStarted = {
	runId: string,
};

export type IdRequest = {
	id: string,
};

export type InstallationDto = {
	id: string,
	providerId: string,
	packageKind: string,
	packageName: string,
	scope: string,
	installPath: string | null,
	executables: ExecutableDto[],
	installedVersion: string | null,
	hidden: boolean,
};

export type LogRetentionDto = {
	maxFiles: number,
	maxTotalBytes: string,
};

export type ManifestDocumentDto = {
	fileName: string,
	revision: string | null,
	contents: string | null,
};

export type ManifestInputDto = {
	fileName: string,
	contents: string,
};

export type ManifestReadRequestDto = {
	fileName: string,
};

export type ManifestValidationDto = {
	fileName: string,
	manifestId: string,
	normalizedToml: string,
};

export type McpAction = "import" | "upsert" | "toggle" | "delete" | "sync" | "restore" | "delete_backup";

export type McpBindingView = {
	targetId: string,
	key: string,
	desiredEnabled: boolean,
	observedState: string,
	extraJson: string,
};

export type McpCandidate = {
	id: string,
	targetId: string,
	key: string,
	transport: McpTransport,
	configJson: string,
	enabled: boolean,
};

export type McpChangedEventDto = {
	revision: string,
	sequence: string,
	runId: string,
	resourceIds: string[],
};

export type McpEdit = {
	id: string | null,
	name: string,
	description: string,
	transport: McpTransport,
	configJson: string,
	secrets: { [key in string]: SecretEdit },
	bindings: McpBindingView[],
};

export type McpOperationRequest = {
	action: McpAction,
	serverIds: string[],
	candidateIds: string[],
	targetIds: string[],
	enabled: boolean,
	edit: McpEdit | null,
	importJson: string | null,
	backupId: string | null,
};

export type McpScan = {
	candidates: McpCandidate[],
	errors: Diagnostic[],
};

export type McpServerView = {
	id: string,
	name: string,
	description: string,
	transport: McpTransport,
	configJson: string,
	bindings: McpBindingView[],
	pendingDelete: boolean,
};

export type McpSnapshot = {
	revision: string,
	servers: McpServerView[],
};

export type McpTransport = "stdio" | "http" | "sse";

export type OperationStepView = {
	targetId: string,
	path: string,
	action: string,
	before: string,
	after: string,
	conflict: string | null,
};

export type PreviewRequestDto = {
	selections: UpdateSelectionDto[],
};

export type ProviderErrorDto = {
	providerId: string,
	operation: string,
	recoverability: string,
	summary: string,
};

export type ProviderRefreshReportDto = {
	providerId: string,
	enabled: boolean,
	status: ProviderStatusDto | null,
	errors: ProviderErrorDto[],
	refreshedAt: string,
};

export type ProviderStatusDto = {
	available: boolean,
	version: string | null,
	detail: string | null,
};

export type RefreshPhaseDto = "started" | "progress" | "completed" | "failed";

export type RefreshProgressEventDto = {
	requestId: string,
	sequence: string,
	phase: RefreshPhaseDto,
	message: string,
	providerId: string | null,
	completed: number | null,
	total: number | null,
};

export type RefreshRequestDto = {
	scope: RefreshScopeDto,
	force: boolean,
};

export type RefreshScopeDto = { scope: "all" } | { scope: "provider"; providerId: string } | { scope: "tool"; toolId: string };

export type ResourceKind = "skill" | "mcp";

export type RunDto = {
	id: string,
	toolId: string | null,
	subject: RunSubject,
	operation: string | null,
	resourceNames: string[],
	componentIds: string[],
	status: string,
	createdAt: string,
	startedAt: string | null,
	finishedAt: string | null,
	batchId: string | null,
	retryOf: string | null,
	hasLog: boolean,
	summary: RunSummaryDto | null,
};

export type RunHistoryDto = {
	runs: RunDto[],
};

export type RunLogDto = {
	runId: string,
	entries: RunLogEntryDto[],
};

export type RunLogEntryDto = {
	sequence: string,
	timestamp: string,
	stream: string,
	message: string,
};

export type RunLogRequestDto = {
	runId: string,
};

export type RunOutputChunkDto = {
	sequence: string,
	stream: RunOutputStreamDto,
	message: string,
};

export type RunOutputEventDto = {
	runId: string,
	firstSequence: string,
	lastSequence: string,
	timestamp: string,
	chunks: RunOutputChunkDto[],
};

export type RunOutputStreamDto = "stdout" | "stderr" | "system";

export type RunStateEventDto = {
	runId: string,
	sequence: string,
	timestamp: string,
	state: RunStateKindDto,
};

export type RunStateKindDto = { kind: "state_changed"; status: string } | { kind: "exit"; code: number | null };

export type RunSubject = "tool_update" | "skill" | "mcp";

export type RunSummaryDto = {
	exitCode: number | null,
	outputTail: string,
	verification: VerificationStatusDto | null,
	error: string | null,
};

export type SaveAgentsRequest = {
	expectedRevision: string,
	overrides: { [key in string]: AgentOverride },
};

export type SaveManifestRequestDto = {
	fileName: string,
	contents: string,
	expectedRevision: string | null,
};

export type SaveSettingsRequestDto = {
	expectedRevision: string,
	settings: SettingsValueDto,
};

export type SaveSourceRequest = {
	expectedRevision: string,
	source: SkillSource,
};

export type SavedManifestDto = {
	revision: string,
	validation: ManifestValidationDto,
	snapshot: SnapshotDto,
};

export type SearchRequest = {
	requestId: string,
	query: string,
};

export type SearchSkill = {
	name: string,
	repository: string,
	skillId: string,
};

export type SecretEdit = { action: "keep" } | { action: "set"; value: string } | { action: "remove" };

export type SettingsDocumentDto = {
	revision: string,
	settings: SettingsValueDto,
};

export type SettingsValueDto = {
	providerEnabled: { [key in string]: boolean },
	defaultTimeoutSeconds: string,
	logRetention: LogRetentionDto,
	executableOverrides: { [key in string]: string },
	componentStrategies: { [key in string]: { [key in string]: string } },
};

export type SkillAction = "install" | "import" | "adopt" | "toggle" | "update" | "uninstall" | "restore" | "delete_backup";

export type SkillCandidate = {
	id: string,
	name: string,
	description: string,
	directoryName: string,
	path: string,
	canonicalPath: string,
	linkTarget: string | null,
	contentHash: string,
	content: string,
	targetIds: string[],
	origin: SkillOrigin | null,
};

export type SkillDeployment = {
	targetId: string,
	path: string,
	desiredEnabled: boolean,
	mode: DeployMode,
	lastAppliedHash: string | null,
	observedState: string,
};

export type SkillDiscovery = {
	candidates: SkillCandidate[],
	errors: Diagnostic[],
	checkedAt: string,
};

export type SkillOperationRequest = {
	action: SkillAction,
	skillIds: string[],
	candidateIds: string[],
	targetIds: string[],
	enabled: boolean,
	mode: DeployMode,
	backupId: string | null,
};

export type SkillOrigin = {
	source: SkillSource,
	relativePath: string,
	resolvedRevision: string | null,
};

export type SkillRecord = {
	id: string,
	name: string,
	description: string,
	directoryName: string,
	origin: SkillOrigin | null,
	contentHash: string,
	updatedAt: string,
	deployments: SkillDeployment[],
	pendingDelete: boolean,
};

export type SkillSource = {
	id: string,
	kind: SourceKind,
	uri: string,
	requestedRef: string | null,
	enabled: boolean,
};

export type SkillUpdate = {
	skillId: string,
	status: string,
	message: string,
	candidateId: string | null,
};

export type SkillsSnapshot = {
	revision: string,
	sources: SkillSource[],
	skills: SkillRecord[],
};

export type SnapshotDto = {
	schemaRevision: number,
	tools: ToolDto[],
	installations: InstallationDto[],
	providers: ProviderRefreshReportDto[],
	catalogDiagnostics: CatalogDiagnosticDto[],
	catalogErrors: CatalogErrorDto[],
	configRevision: string,
	stateRevision: string,
	environmentRevision: string,
	refreshedAt: string | null,
};

export type SourceKind = "local" | "zip" | "github";

export type StatusReasonDto = {
	code: string,
	summary: string,
	retryable: boolean,
};

export type StrategyDto = {
	id: string,
	displayName: string,
	kind: StrategyKindDto,
	enabled: boolean,
};

export type StrategyKindDto = { kind: "provider_default" } | { kind: "command"; program: string; args: string[] } | { kind: "package_manager"; manager: string; args: string[] };

export type TargetResult = {
	targetId: string,
	path: string,
	status: string,
	message: string,
};

export type ToolDto = {
	id: string,
	displayName: string,
	installationIds: string[],
	components: ComponentDto[],
	categories: string[],
	homepage: string | null,
	hidden: boolean,
	status: ToolStatusDto,
};

export type ToolStateEventDto = {
	sequence: string,
	stateRevision: string,
	toolIds: string[],
};

export type ToolStatusDto = {
	status: string,
	hasUpdates: boolean | null,
	failedComponents: number | null,
	unknownComponents: number | null,
	unsupportedComponents: number | null,
};

export type UpdatePlanDto = {
	planId: string,
	planHash: string,
	toolId: string,
	installationId: string,
	componentId: string,
	strategyId: string,
	command: CommandSpecDto,
	configRevision: string,
	environmentRevision: string,
	versionSnapshot: string,
	createdAt: string,
	expiresAt: string,
};

export type UpdateSelectionDto = {
	toolId: string,
	componentId: string,
	strategyId: string | null,
	targetVersion: string | null,
};

export type VerificationStatusDto = {
	status: string,
	reason: StatusReasonDto | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

