// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	snapshot: () => typedError<SnapshotDto, ApiErrorDto>(__TAURI_INVOKE("snapshot")),
	refresh: (request: RefreshRequestDto) => typedError<SnapshotDto, ApiErrorDto>(__TAURI_INVOKE("refresh", { request })),
	preview: (request: PreviewRequestDto) => typedError<UpdatePlanDto[], ApiErrorDto>(__TAURI_INVOKE("preview", { request })),
	confirm: (request: ConfirmRequestDto) => typedError<ConfirmResponseDto, ApiErrorDto>(__TAURI_INVOKE("confirm", { request })),
	cancel: (request: CancelRequestDto) => typedError<CancelResponseDto, ApiErrorDto>(__TAURI_INVOKE("cancel", { request })),
	runHistory: () => typedError<RunHistoryDto, ApiErrorDto>(__TAURI_INVOKE("run_history")),
	runLog: (request: RunLogRequestDto) => typedError<RunLogDto, ApiErrorDto>(__TAURI_INVOKE("run_log", { request })),
	settings: () => typedError<SettingsDocumentDto, ApiErrorDto>(__TAURI_INVOKE("settings")),
	saveSettings: (request: SaveSettingsRequestDto) => typedError<SettingsDocumentDto, ApiErrorDto>(__TAURI_INVOKE("save_settings", { request })),
	validateManifest: (request: ManifestInputDto) => typedError<ManifestValidationDto, ApiErrorDto>(__TAURI_INVOKE("validate_manifest", { request })),
	readManifest: (request: ManifestReadRequestDto) => typedError<ManifestDocumentDto, ApiErrorDto>(__TAURI_INVOKE("read_manifest", { request })),
	saveManifest: (request: SaveManifestRequestDto) => typedError<SavedManifestDto, ApiErrorDto>(__TAURI_INVOKE("save_manifest", { request })),
};

/** Events */
export const events = {
	refreshProgress: makeEvent<RefreshProgressEventDto>("refresh-progress"),
	runOutput: makeEvent<RunOutputEventDto>("run-output"),
	runState: makeEvent<RunStateEventDto>("run-state"),
	toolState: makeEvent<ToolStateEventDto>("tool-state"),
};

/* Types */
export type ApiErrorCode = "invalid_request" | "not_found" | "invalid_plan" | "conflict" | "unavailable" | "internal";

export type ApiErrorDto = {
	code: ApiErrorCode,
	message: string,
	retryable: boolean,
	details: { [key in string]: string },
};

export type CancelDispositionDto = "cancellation_requested" | "already_finished";

export type CancelRequestDto = {
	runId: string,
};

export type CancelResponseDto = {
	runId: string,
	disposition: CancelDispositionDto,
};

export type CatalogDiagnosticDto = {
	source: string,
	manifestId: string,
	kind: string,
	matchingToolIds: string[],
	message: string,
};

export type CatalogErrorDto = {
	source: string,
	fieldPath: string,
	kind: string,
	message: string,
	hint: string,
	line: number | null,
	column: number | null,
};

export type CommandSpecDto = {
	program: string,
	args: string[],
	cwd: string | null,
	env: { [key in string]: EnvironmentValueDto },
	timeoutSeconds: string,
	successExitCodes: number[],
	networkRequired: boolean,
	postCheck: CommandSpecDto | null,
	displayCommand: string,
};

export type ComponentDto = {
	id: string,
	displayName: string,
	installationId: string | null,
	strategies: StrategyDto[],
	defaultStrategy: string | null,
	installedVersion: string | null,
	latestVersion: string | null,
	status: ComponentStatusDto,
};

export type ComponentStatusDto = {
	status: string,
	reason: StatusReasonDto | null,
	verification: VerificationStatusDto | null,
};

export type ConfirmRequestDto = {
	planId: string,
	planHash: string,
};

export type ConfirmResponseDto = {
	execution: ExecutionResultDto,
	snapshot: SnapshotDto,
};

export type EnvironmentValueDto = {
	value: string,
	sensitive: boolean,
};

export type ExecutableDto = {
	name: string,
	path: string,
};

export type ExecutionResultDto = {
	runId: string,
	status: string,
	exitCode: number | null,
	startedAt: string,
	finishedAt: string,
	outputTail: string,
	verification: VerificationStatusDto | null,
};

export type InstallationDto = {
	id: string,
	providerId: string,
	packageKind: string,
	packageName: string,
	scope: string,
	installPath: string | null,
	executables: ExecutableDto[],
	installedVersion: string | null,
	hidden: boolean,
};

export type LogRetentionDto = {
	maxFiles: number,
	maxTotalBytes: string,
};

export type ManifestDocumentDto = {
	fileName: string,
	revision: string | null,
	contents: string | null,
};

export type ManifestInputDto = {
	fileName: string,
	contents: string,
};

export type ManifestReadRequestDto = {
	fileName: string,
};

export type ManifestValidationDto = {
	fileName: string,
	manifestId: string,
	normalizedToml: string,
};

export type PreviewRequestDto = {
	selections: UpdateSelectionDto[],
};

export type ProviderErrorDto = {
	providerId: string,
	operation: string,
	recoverability: string,
	summary: string,
};

export type ProviderRefreshReportDto = {
	providerId: string,
	enabled: boolean,
	status: ProviderStatusDto | null,
	errors: ProviderErrorDto[],
	refreshedAt: string,
};

export type ProviderStatusDto = {
	available: boolean,
	version: string | null,
	detail: string | null,
};

export type RefreshPhaseDto = "started" | "completed" | "failed";

export type RefreshProgressEventDto = {
	requestId: string,
	sequence: string,
	phase: RefreshPhaseDto,
	message: string,
};

export type RefreshRequestDto = {
	scope: RefreshScopeDto,
	force: boolean,
};

export type RefreshScopeDto = { scope: "all" } | { scope: "provider"; providerId: string } | { scope: "tool"; toolId: string };

export type RunDto = {
	id: string,
	toolId: string,
	componentIds: string[],
	status: string,
	createdAt: string,
	startedAt: string | null,
	finishedAt: string | null,
	batchId: string | null,
	retryOf: string | null,
	hasLog: boolean,
	summary: RunSummaryDto | null,
};

export type RunHistoryDto = {
	runs: RunDto[],
};

export type RunLogDto = {
	runId: string,
	entries: RunLogEntryDto[],
};

export type RunLogEntryDto = {
	sequence: string,
	timestamp: string,
	stream: string,
	message: string,
};

export type RunLogRequestDto = {
	runId: string,
};

export type RunOutputChunkDto = {
	sequence: string,
	stream: RunOutputStreamDto,
	message: string,
};

export type RunOutputEventDto = {
	runId: string,
	firstSequence: string,
	lastSequence: string,
	timestamp: string,
	chunks: RunOutputChunkDto[],
};

export type RunOutputStreamDto = "stdout" | "stderr" | "system";

export type RunStateEventDto = {
	runId: string,
	sequence: string,
	timestamp: string,
	state: RunStateKindDto,
};

export type RunStateKindDto = { kind: "state_changed"; status: string } | { kind: "exit"; code: number | null };

export type RunSummaryDto = {
	exitCode: number | null,
	outputTail: string,
	verification: VerificationStatusDto | null,
	error: string | null,
};

export type SaveManifestRequestDto = {
	fileName: string,
	contents: string,
	expectedRevision: string | null,
};

export type SaveSettingsRequestDto = {
	expectedRevision: string,
	settings: SettingsValueDto,
};

export type SavedManifestDto = {
	revision: string,
	validation: ManifestValidationDto,
	snapshot: SnapshotDto,
};

export type SettingsDocumentDto = {
	revision: string,
	settings: SettingsValueDto,
};

export type SettingsValueDto = {
	providerEnabled: { [key in string]: boolean },
	defaultTimeoutSeconds: string,
	logRetention: LogRetentionDto,
	executableOverrides: { [key in string]: string },
	componentStrategies: { [key in string]: { [key in string]: string } },
};

export type SnapshotDto = {
	schemaRevision: number,
	tools: ToolDto[],
	installations: InstallationDto[],
	providers: ProviderRefreshReportDto[],
	catalogDiagnostics: CatalogDiagnosticDto[],
	catalogErrors: CatalogErrorDto[],
	configRevision: string,
	stateRevision: string,
	environmentRevision: string,
	refreshedAt: string | null,
};

export type StatusReasonDto = {
	code: string,
	summary: string,
	retryable: boolean,
};

export type StrategyDto = {
	id: string,
	displayName: string,
	kind: StrategyKindDto,
	enabled: boolean,
};

export type StrategyKindDto = { kind: "provider_default" } | { kind: "command"; program: string; args: string[] } | { kind: "package_manager"; manager: string; args: string[] };

export type ToolDto = {
	id: string,
	displayName: string,
	installationIds: string[],
	components: ComponentDto[],
	categories: string[],
	homepage: string | null,
	hidden: boolean,
	status: ToolStatusDto,
};

export type ToolStateEventDto = {
	sequence: string,
	stateRevision: string,
	toolIds: string[],
};

export type ToolStatusDto = {
	status: string,
	hasUpdates: boolean | null,
	failedComponents: number | null,
	unknownComponents: number | null,
	unsupportedComponents: number | null,
};

export type UpdatePlanDto = {
	planId: string,
	planHash: string,
	toolId: string,
	installationId: string,
	componentId: string,
	strategyId: string,
	command: CommandSpecDto,
	configRevision: string,
	environmentRevision: string,
	versionSnapshot: string,
	createdAt: string,
	expiresAt: string,
};

export type UpdateSelectionDto = {
	toolId: string,
	componentId: string,
	strategyId: string | null,
	targetVersion: string | null,
};

export type VerificationStatusDto = {
	status: string,
	reason: StatusReasonDto | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

